/*
 * Acceptable-use splash / self-certification modal for Open WebUI, plus the
 * runtime half of the UI lockdown (sidebar pinned to its icon rail, no chat
 * search).
 *
 * Mounted over the empty placeholder Open WebUI ships at
 *   /app/backend/open_webui/static/loader.js
 * which its page template (src/app.html) already loads as:
 *   <script src="/static/loader.js" defer crossorigin="use-credentials"></script>
 *
 * The CSS half lives in branding/custom.css, mounted the same way.
 *
 * No fork, no image rebuild. See branding/README.md.
 *
 * NOTE: this is a speed bump plus an acceptance record, NOT a security control.
 * The API is still reachable directly (LiteLLM at /litellm/) without seeing this.
 */
(function () {
	'use strict';

	// Bump this when the wording changes — everyone gets re-prompted immediately
	// rather than at their next login, and the new acceptances are recorded under
	// the new key.
	var CONSENT_KEY = 'aup_accepted_v1';

	// Which login we last showed the modal for. The value is the JWT itself:
	// Open WebUI issues a new one per sign-in and keeps it stable across reloads,
	// so comparing against it prompts exactly once per login.
	var SEEN_KEY = 'aup_seen_token_v1';

	// Rolling audit trail in the user's server-side info blob.
	var LOG_KEY = 'aup_accepted_log';
	var LOG_MAX = 20;

	var TITLE = 'Authorized Use Only';

	// Keep as an array of paragraphs. Plain text; no HTML is interpreted.
	var BODY = [
		'This is an internal test environment for evaluating large language models. By continuing you certify that you understand and agree to the following:',
		'Do not enter PII, PHI, or any sensitive or protected information into this system.',
		'Responses are generated by an AI model and may be inaccurate, incomplete, or misleading. Verify anything you intend to rely on.',
		'Do not use output from this system as the sole basis for any clinical, legal, financial, or personnel decision.',
		'Your prompts and responses may be logged and reviewed for security and quality purposes.'
	];

	var BUTTON = 'I Agree';

	// ------------------------------------------------------------ UI lockdown

	// Open WebUI seeds its showSidebar store from localStorage.sidebar in the
	// Sidebar component's onMount. This script runs before the SPA hydrates, so
	// setting it here decides the initial state — the sidebar comes up as the
	// 42px icon rail, and the chat area keeps its full width.
	function railSidebar() {
		try {
			localStorage.sidebar = 'false';
		} catch (e) {
			/* private mode — the watchdog below still collapses it */
		}
	}

	railSidebar();

	// Open WebUI binds its shortcuts with a non-capturing keydown listener on
	// document, so a capture-phase listener here runs first and can swallow them.
	//   Cmd/Ctrl+K       -> Search      (the SearchModal is always mounted; hiding
	//                                    the button in CSS does not disable this)
	//   Cmd/Ctrl+Shift+S -> Toggle Sidebar
	// Both chords are user-rebindable in Settings, which is what the watchdog is
	// for. Note this also swallows the browser's own Ctrl+K.
	document.addEventListener(
		'keydown',
		function (e) {
			if (!(e.metaKey || e.ctrlKey)) return;
			var k = (e.key || '').toLowerCase();
			if ((k === 'k' && !e.shiftKey) || (k === 's' && e.shiftKey)) {
				e.preventDefault();
				e.stopImmediatePropagation();
			}
		},
		true
	);

	// Belt and braces: whatever expands the sidebar — a rebound shortcut, a stale
	// selector, devtools — collapse it back. Only the expanded container carries
	// data-state; the rail reuses id="sidebar" without it. The collapse control
	// is hidden by custom.css, but .click() still fires on a display:none node.
	//
	// Desktop only. Under Open WebUI's mobile breakpoint the rail is not rendered
	// at all, so collapsing there would leave no route to chat history or the
	// user menu — mobile keeps the normal hamburger + overlay.
	setInterval(function () {
		if (window.innerWidth < 768) return;
		var el = document.getElementById('sidebar');
		if (!el || el.getAttribute('data-state') !== 'true') return;
		railSidebar();
		var collapse = el.querySelector('.sidebar button');
		if (collapse) collapse.click();
	}, 500);

	// ---------------------------------------------------------------- storage

	function token() {
		try {
			return localStorage.token || null;
		} catch (e) {
			return null;
		}
	}

	function authHeaders() {
		return { Authorization: 'Bearer ' + token(), 'Content-Type': 'application/json' };
	}

	// Gate on login identity, not on a permanent flag: prompt whenever the
	// current JWT is not the one we last recorded an acceptance for. That is once
	// per sign-in — reloads reuse the same token and do not re-prompt.
	function needsPrompt() {
		try {
			return localStorage.getItem(SEEN_KEY) !== token();
		} catch (e) {
			return true; // no storage — prompt every load rather than never
		}
	}

	// Server-side, per-user. Ties each click to an LDAP identity and survives
	// cache clears, which localStorage alone would not. The local SEEN_KEY is
	// what suppresses re-prompting; this is purely the record.
	function recordAcceptance() {
		var stamp = new Date().toISOString();

		try {
			localStorage.setItem(SEEN_KEY, token());
		} catch (e) {
			/* private mode — user gets re-prompted on reload, which is the safe
			   direction to fail */
		}

		// Read-modify-write so the log accumulates. PATCH-style merge on the way
		// back, so other keys in the user's info blob are preserved.
		return fetch('/api/v1/users/user/info', { headers: authHeaders() })
			.then(function (r) {
				return r.ok ? r.json() : null;
			})
			.catch(function () {
				return null;
			})
			.then(function (info) {
				var log = (info && Array.isArray(info[LOG_KEY]) ? info[LOG_KEY] : []).concat(stamp);
				var body = { };
				body[CONSENT_KEY] = stamp;
				body[LOG_KEY] = log.slice(-LOG_MAX);

				return fetch('/api/v1/users/user/info/update', {
					method: 'POST',
					headers: authHeaders(),
					body: JSON.stringify(body)
				});
			})
			.catch(function () {
				/* best effort */
			});
	}

	// ------------------------------------------------------------------- view

	var CSS = [
		'#aup-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;',
		'align-items:center;justify-content:center;padding:1rem;',
		'background:rgba(0,0,0,.72);backdrop-filter:blur(4px);',
		'font-family:ui-sans-serif,-apple-system,system-ui,"Segoe UI",Roboto,sans-serif}',
		'#aup-box{max-width:44rem;width:100%;max-height:88vh;overflow-y:auto;',
		'background:#fff;color:#171717;border-radius:.75rem;padding:1.75rem;',
		'box-shadow:0 24px 60px rgba(0,0,0,.45)}',
		'html.dark #aup-box{background:#1c1c1c;color:#ededed}',
		'#aup-box h2{margin:0 0 1rem;font-size:1.25rem;font-weight:600;line-height:1.3}',
		'#aup-box p{margin:0 0 .75rem;font-size:.9rem;line-height:1.6}',
		'#aup-box p.aup-lead{font-size:.95rem}',
		'#aup-box ul{margin:0 0 1.25rem;padding-left:1.25rem}',
		'#aup-box li{margin-bottom:.5rem;font-size:.9rem;line-height:1.6}',
		'#aup-actions{display:flex;justify-content:flex-end;padding-top:.5rem;',
		'border-top:1px solid rgba(128,128,128,.25)}',
		'#aup-accept{margin-top:1rem;padding:.6rem 1.6rem;border:0;border-radius:.5rem;',
		'background:#171717;color:#fff;font-size:.9rem;font-weight:500;cursor:pointer}',
		'html.dark #aup-accept{background:#ededed;color:#171717}',
		'#aup-accept:hover{opacity:.85}',
		'#aup-accept:disabled{opacity:.5;cursor:default}'
	].join('');

	function show() {
		if (document.getElementById('aup-overlay')) return;

		var style = document.createElement('style');
		style.textContent = CSS;
		document.head.appendChild(style);

		var overlay = document.createElement('div');
		overlay.id = 'aup-overlay';
		overlay.setAttribute('role', 'dialog');
		overlay.setAttribute('aria-modal', 'true');
		overlay.setAttribute('aria-labelledby', 'aup-title');

		var box = document.createElement('div');
		box.id = 'aup-box';

		var h2 = document.createElement('h2');
		h2.id = 'aup-title';
		h2.textContent = TITLE;
		box.appendChild(h2);

		// First paragraph is the lead-in; the rest render as a list of terms.
		var lead = document.createElement('p');
		lead.className = 'aup-lead';
		lead.textContent = BODY[0];
		box.appendChild(lead);

		if (BODY.length > 1) {
			var ul = document.createElement('ul');
			BODY.slice(1).forEach(function (item) {
				var li = document.createElement('li');
				li.textContent = item;
				ul.appendChild(li);
			});
			box.appendChild(ul);
		}

		var actions = document.createElement('div');
		actions.id = 'aup-actions';

		var btn = document.createElement('button');
		btn.id = 'aup-accept';
		btn.type = 'button';
		btn.textContent = BUTTON;
		btn.addEventListener('click', function () {
			btn.disabled = true;
			recordAcceptance().then(function () {
				overlay.remove();
				document.documentElement.style.overflow = '';
			});
		});

		actions.appendChild(btn);
		box.appendChild(actions);
		overlay.appendChild(box);
		document.body.appendChild(overlay);

		document.documentElement.style.overflow = 'hidden';
		btn.focus();

		// Keep focus inside the dialog — the only way out is the button.
		overlay.addEventListener('keydown', function (e) {
			if (e.key === 'Tab') e.preventDefault();
		});
	}

	// ------------------------------------------------------------------ start

	// The script is deferred, but the SPA mounts later and the login page has no
	// token yet. Poll for an authenticated session — and keep polling for the
	// lifetime of the page, so a logout followed by a fresh login re-prompts even
	// if it happens without a full page load.
	setInterval(function () {
		if (!token() || !document.body) return;
		if (!needsPrompt()) return;
		show();
	}, 300);
})();
