/*
 * Acceptable-use splash / self-certification modal for Open WebUI.
 *
 * Mounted over the empty placeholder Open WebUI ships at
 *   /app/backend/open_webui/static/loader.js
 * which its page template (src/app.html) already loads as:
 *   <script src="/static/loader.js" defer crossorigin="use-credentials"></script>
 *
 * No fork, no image rebuild. See branding/README.md.
 *
 * NOTE: this is a speed bump plus an acceptance record, NOT a security control.
 * The API is still reachable directly (LiteLLM at /litellm/) without seeing this.
 */
(function () {
	'use strict';

	// Bump this when the wording changes — everyone gets re-prompted.
	var CONSENT_KEY = 'aup_accepted_v1';

	var TITLE = 'Authorized Use Only';

	// Keep as an array of paragraphs. Plain text; no HTML is interpreted.
	var BODY = [
		'This is an internal test environment for evaluating large language models. By continuing you certify that you understand and agree to the following:',
		'Do not enter PII, PHI, or any sensitive or protected information into this system.',
		'Responses are generated by an AI model and may be inaccurate, incomplete, or misleading. Verify anything you intend to rely on.',
		'Do not use output from this system as the sole basis for any clinical, legal, financial, or personnel decision.',
		'Your prompts and responses may be logged and reviewed for security and quality purposes.'
	];

	var BUTTON = 'I Agree';

	// ---------------------------------------------------------------- storage

	function token() {
		try {
			return localStorage.token || null;
		} catch (e) {
			return null;
		}
	}

	function authHeaders() {
		return { Authorization: 'Bearer ' + token(), 'Content-Type': 'application/json' };
	}

	// Server-side, per-user. Survives cache clears and follows the account across
	// devices — which a cookie or bare localStorage would not.
	function hasAccepted() {
		return fetch('/api/v1/users/user/info', { headers: authHeaders() })
			.then(function (r) {
				return r.ok ? r.json() : null;
			})
			.then(function (info) {
				return !!(info && info[CONSENT_KEY]);
			})
			.catch(function () {
				// API unreachable — fall back to local so we neither hard-block
				// the user nor re-prompt them on every reload.
				try {
					return !!localStorage.getItem(CONSENT_KEY);
				} catch (e) {
					return false;
				}
			});
	}

	function recordAcceptance() {
		var stamp = new Date().toISOString();
		var body = {};
		body[CONSENT_KEY] = stamp;

		try {
			localStorage.setItem(CONSENT_KEY, stamp);
		} catch (e) {
			/* private mode — server record below is the one that matters */
		}

		// PATCH-style merge; other keys in the user's info blob are preserved.
		return fetch('/api/v1/users/user/info/update', {
			method: 'POST',
			headers: authHeaders(),
			body: JSON.stringify(body)
		}).catch(function () {
			/* best effort */
		});
	}

	// ------------------------------------------------------------------- view

	var CSS = [
		'#aup-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;',
		'align-items:center;justify-content:center;padding:1rem;',
		'background:rgba(0,0,0,.72);backdrop-filter:blur(4px);',
		'font-family:ui-sans-serif,-apple-system,system-ui,"Segoe UI",Roboto,sans-serif}',
		'#aup-box{max-width:44rem;width:100%;max-height:88vh;overflow-y:auto;',
		'background:#fff;color:#171717;border-radius:.75rem;padding:1.75rem;',
		'box-shadow:0 24px 60px rgba(0,0,0,.45)}',
		'html.dark #aup-box{background:#1c1c1c;color:#ededed}',
		'#aup-box h2{margin:0 0 1rem;font-size:1.25rem;font-weight:600;line-height:1.3}',
		'#aup-box p{margin:0 0 .75rem;font-size:.9rem;line-height:1.6}',
		'#aup-box p.aup-lead{font-size:.95rem}',
		'#aup-box ul{margin:0 0 1.25rem;padding-left:1.25rem}',
		'#aup-box li{margin-bottom:.5rem;font-size:.9rem;line-height:1.6}',
		'#aup-actions{display:flex;justify-content:flex-end;padding-top:.5rem;',
		'border-top:1px solid rgba(128,128,128,.25)}',
		'#aup-accept{margin-top:1rem;padding:.6rem 1.6rem;border:0;border-radius:.5rem;',
		'background:#171717;color:#fff;font-size:.9rem;font-weight:500;cursor:pointer}',
		'html.dark #aup-accept{background:#ededed;color:#171717}',
		'#aup-accept:hover{opacity:.85}',
		'#aup-accept:disabled{opacity:.5;cursor:default}'
	].join('');

	function show() {
		if (document.getElementById('aup-overlay')) return;

		var style = document.createElement('style');
		style.textContent = CSS;
		document.head.appendChild(style);

		var overlay = document.createElement('div');
		overlay.id = 'aup-overlay';
		overlay.setAttribute('role', 'dialog');
		overlay.setAttribute('aria-modal', 'true');
		overlay.setAttribute('aria-labelledby', 'aup-title');

		var box = document.createElement('div');
		box.id = 'aup-box';

		var h2 = document.createElement('h2');
		h2.id = 'aup-title';
		h2.textContent = TITLE;
		box.appendChild(h2);

		// First paragraph is the lead-in; the rest render as a list of terms.
		var lead = document.createElement('p');
		lead.className = 'aup-lead';
		lead.textContent = BODY[0];
		box.appendChild(lead);

		if (BODY.length > 1) {
			var ul = document.createElement('ul');
			BODY.slice(1).forEach(function (item) {
				var li = document.createElement('li');
				li.textContent = item;
				ul.appendChild(li);
			});
			box.appendChild(ul);
		}

		var actions = document.createElement('div');
		actions.id = 'aup-actions';

		var btn = document.createElement('button');
		btn.id = 'aup-accept';
		btn.type = 'button';
		btn.textContent = BUTTON;
		btn.addEventListener('click', function () {
			btn.disabled = true;
			recordAcceptance().then(function () {
				overlay.remove();
				document.documentElement.style.overflow = '';
			});
		});

		actions.appendChild(btn);
		box.appendChild(actions);
		overlay.appendChild(box);
		document.body.appendChild(overlay);

		document.documentElement.style.overflow = 'hidden';
		btn.focus();

		// Keep focus inside the dialog — the only way out is the button.
		overlay.addEventListener('keydown', function (e) {
			if (e.key === 'Tab') e.preventDefault();
		});
	}

	// ------------------------------------------------------------------ start

	// The script is deferred, but the SPA mounts later and the login page has no
	// token yet. Poll until the user is actually authenticated, then check once.
	var waited = 0;
	var timer = setInterval(function () {
		waited += 300;
		if (waited > 120000) {
			clearInterval(timer); // never logged in; give up quietly
			return;
		}
		if (!token() || !document.body) return;

		clearInterval(timer);
		hasAccepted().then(function (accepted) {
			if (!accepted) show();
		});
	}, 300);
})();
